package com.betterit.kaligia.dao.model.kaligia;

import java.io.Serializable;
import java.util.Date;

public class Device implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.device.device_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private Integer deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.device.name
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.device.type
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.device.manufacturer
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private String manufacturer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.device.model
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private String model;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.device.status
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.device.creation_date
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private Date creationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.device.created_by
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private Integer createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table kaligia.device
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.device.device_id
	 * @return  the value of kaligia.device.device_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public Integer getDeviceId() {
		return deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.device.device_id
	 * @param deviceId  the value for kaligia.device.device_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setDeviceId(Integer deviceId) {
		this.deviceId = deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.device.name
	 * @return  the value of kaligia.device.name
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.device.name
	 * @param name  the value for kaligia.device.name
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.device.type
	 * @return  the value of kaligia.device.type
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.device.type
	 * @param type  the value for kaligia.device.type
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.device.manufacturer
	 * @return  the value of kaligia.device.manufacturer
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public String getManufacturer() {
		return manufacturer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.device.manufacturer
	 * @param manufacturer  the value for kaligia.device.manufacturer
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer == null ? null : manufacturer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.device.model
	 * @return  the value of kaligia.device.model
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public String getModel() {
		return model;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.device.model
	 * @param model  the value for kaligia.device.model
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setModel(String model) {
		this.model = model == null ? null : model.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.device.status
	 * @return  the value of kaligia.device.status
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.device.status
	 * @param status  the value for kaligia.device.status
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.device.creation_date
	 * @return  the value of kaligia.device.creation_date
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public Date getCreationDate() {
		return creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.device.creation_date
	 * @param creationDate  the value for kaligia.device.creation_date
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.device.created_by
	 * @return  the value of kaligia.device.created_by
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public Integer getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.device.created_by
	 * @param createdBy  the value for kaligia.device.created_by
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.device
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", deviceId=").append(deviceId);
		sb.append(", name=").append(name);
		sb.append(", type=").append(type);
		sb.append(", manufacturer=").append(manufacturer);
		sb.append(", model=").append(model);
		sb.append(", status=").append(status);
		sb.append(", creationDate=").append(creationDate);
		sb.append(", createdBy=").append(createdBy);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}