package com.betterit.kaligia.dao.model.kaligia;

import java.util.ArrayList;
import java.util.List;

public class DeviceSpecExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table kaligia.devicespec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table kaligia.devicespec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table kaligia.devicespec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.devicespec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public DeviceSpecExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.devicespec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.devicespec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.devicespec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.devicespec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.devicespec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.devicespec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.devicespec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.devicespec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.devicespec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.devicespec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table kaligia.devicespec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andDeviceIdIsNull() {
			addCriterion("device_id is null");
			return (Criteria) this;
		}

		public Criteria andDeviceIdIsNotNull() {
			addCriterion("device_id is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceIdEqualTo(Integer value) {
			addCriterion("device_id =", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdNotEqualTo(Integer value) {
			addCriterion("device_id <>", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdGreaterThan(Integer value) {
			addCriterion("device_id >", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("device_id >=", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdLessThan(Integer value) {
			addCriterion("device_id <", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdLessThanOrEqualTo(Integer value) {
			addCriterion("device_id <=", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdIn(List<Integer> values) {
			addCriterion("device_id in", values, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdNotIn(List<Integer> values) {
			addCriterion("device_id not in", values, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdBetween(Integer value1, Integer value2) {
			addCriterion("device_id between", value1, value2, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdNotBetween(Integer value1, Integer value2) {
			addCriterion("device_id not between", value1, value2, "deviceId");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andValueIsNull() {
			addCriterion("value is null");
			return (Criteria) this;
		}

		public Criteria andValueIsNotNull() {
			addCriterion("value is not null");
			return (Criteria) this;
		}

		public Criteria andValueEqualTo(String value) {
			addCriterion("value =", value, "value");
			return (Criteria) this;
		}

		public Criteria andValueNotEqualTo(String value) {
			addCriterion("value <>", value, "value");
			return (Criteria) this;
		}

		public Criteria andValueGreaterThan(String value) {
			addCriterion("value >", value, "value");
			return (Criteria) this;
		}

		public Criteria andValueGreaterThanOrEqualTo(String value) {
			addCriterion("value >=", value, "value");
			return (Criteria) this;
		}

		public Criteria andValueLessThan(String value) {
			addCriterion("value <", value, "value");
			return (Criteria) this;
		}

		public Criteria andValueLessThanOrEqualTo(String value) {
			addCriterion("value <=", value, "value");
			return (Criteria) this;
		}

		public Criteria andValueLike(String value) {
			addCriterion("value like", value, "value");
			return (Criteria) this;
		}

		public Criteria andValueNotLike(String value) {
			addCriterion("value not like", value, "value");
			return (Criteria) this;
		}

		public Criteria andValueIn(List<String> values) {
			addCriterion("value in", values, "value");
			return (Criteria) this;
		}

		public Criteria andValueNotIn(List<String> values) {
			addCriterion("value not in", values, "value");
			return (Criteria) this;
		}

		public Criteria andValueBetween(String value1, String value2) {
			addCriterion("value between", value1, value2, "value");
			return (Criteria) this;
		}

		public Criteria andValueNotBetween(String value1, String value2) {
			addCriterion("value not between", value1, value2, "value");
			return (Criteria) this;
		}

		public Criteria andMinValueIsNull() {
			addCriterion("min_value is null");
			return (Criteria) this;
		}

		public Criteria andMinValueIsNotNull() {
			addCriterion("min_value is not null");
			return (Criteria) this;
		}

		public Criteria andMinValueEqualTo(String value) {
			addCriterion("min_value =", value, "minValue");
			return (Criteria) this;
		}

		public Criteria andMinValueNotEqualTo(String value) {
			addCriterion("min_value <>", value, "minValue");
			return (Criteria) this;
		}

		public Criteria andMinValueGreaterThan(String value) {
			addCriterion("min_value >", value, "minValue");
			return (Criteria) this;
		}

		public Criteria andMinValueGreaterThanOrEqualTo(String value) {
			addCriterion("min_value >=", value, "minValue");
			return (Criteria) this;
		}

		public Criteria andMinValueLessThan(String value) {
			addCriterion("min_value <", value, "minValue");
			return (Criteria) this;
		}

		public Criteria andMinValueLessThanOrEqualTo(String value) {
			addCriterion("min_value <=", value, "minValue");
			return (Criteria) this;
		}

		public Criteria andMinValueLike(String value) {
			addCriterion("min_value like", value, "minValue");
			return (Criteria) this;
		}

		public Criteria andMinValueNotLike(String value) {
			addCriterion("min_value not like", value, "minValue");
			return (Criteria) this;
		}

		public Criteria andMinValueIn(List<String> values) {
			addCriterion("min_value in", values, "minValue");
			return (Criteria) this;
		}

		public Criteria andMinValueNotIn(List<String> values) {
			addCriterion("min_value not in", values, "minValue");
			return (Criteria) this;
		}

		public Criteria andMinValueBetween(String value1, String value2) {
			addCriterion("min_value between", value1, value2, "minValue");
			return (Criteria) this;
		}

		public Criteria andMinValueNotBetween(String value1, String value2) {
			addCriterion("min_value not between", value1, value2, "minValue");
			return (Criteria) this;
		}

		public Criteria andMaxValueIsNull() {
			addCriterion("max_value is null");
			return (Criteria) this;
		}

		public Criteria andMaxValueIsNotNull() {
			addCriterion("max_value is not null");
			return (Criteria) this;
		}

		public Criteria andMaxValueEqualTo(String value) {
			addCriterion("max_value =", value, "maxValue");
			return (Criteria) this;
		}

		public Criteria andMaxValueNotEqualTo(String value) {
			addCriterion("max_value <>", value, "maxValue");
			return (Criteria) this;
		}

		public Criteria andMaxValueGreaterThan(String value) {
			addCriterion("max_value >", value, "maxValue");
			return (Criteria) this;
		}

		public Criteria andMaxValueGreaterThanOrEqualTo(String value) {
			addCriterion("max_value >=", value, "maxValue");
			return (Criteria) this;
		}

		public Criteria andMaxValueLessThan(String value) {
			addCriterion("max_value <", value, "maxValue");
			return (Criteria) this;
		}

		public Criteria andMaxValueLessThanOrEqualTo(String value) {
			addCriterion("max_value <=", value, "maxValue");
			return (Criteria) this;
		}

		public Criteria andMaxValueLike(String value) {
			addCriterion("max_value like", value, "maxValue");
			return (Criteria) this;
		}

		public Criteria andMaxValueNotLike(String value) {
			addCriterion("max_value not like", value, "maxValue");
			return (Criteria) this;
		}

		public Criteria andMaxValueIn(List<String> values) {
			addCriterion("max_value in", values, "maxValue");
			return (Criteria) this;
		}

		public Criteria andMaxValueNotIn(List<String> values) {
			addCriterion("max_value not in", values, "maxValue");
			return (Criteria) this;
		}

		public Criteria andMaxValueBetween(String value1, String value2) {
			addCriterion("max_value between", value1, value2, "maxValue");
			return (Criteria) this;
		}

		public Criteria andMaxValueNotBetween(String value1, String value2) {
			addCriterion("max_value not between", value1, value2, "maxValue");
			return (Criteria) this;
		}

		public Criteria andUnitIsNull() {
			addCriterion("unit is null");
			return (Criteria) this;
		}

		public Criteria andUnitIsNotNull() {
			addCriterion("unit is not null");
			return (Criteria) this;
		}

		public Criteria andUnitEqualTo(String value) {
			addCriterion("unit =", value, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitNotEqualTo(String value) {
			addCriterion("unit <>", value, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitGreaterThan(String value) {
			addCriterion("unit >", value, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitGreaterThanOrEqualTo(String value) {
			addCriterion("unit >=", value, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitLessThan(String value) {
			addCriterion("unit <", value, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitLessThanOrEqualTo(String value) {
			addCriterion("unit <=", value, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitLike(String value) {
			addCriterion("unit like", value, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitNotLike(String value) {
			addCriterion("unit not like", value, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitIn(List<String> values) {
			addCriterion("unit in", values, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitNotIn(List<String> values) {
			addCriterion("unit not in", values, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitBetween(String value1, String value2) {
			addCriterion("unit between", value1, value2, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitNotBetween(String value1, String value2) {
			addCriterion("unit not between", value1, value2, "unit");
			return (Criteria) this;
		}

		public Criteria andTunableIsNull() {
			addCriterion("tunable is null");
			return (Criteria) this;
		}

		public Criteria andTunableIsNotNull() {
			addCriterion("tunable is not null");
			return (Criteria) this;
		}

		public Criteria andTunableEqualTo(String value) {
			addCriterion("tunable =", value, "tunable");
			return (Criteria) this;
		}

		public Criteria andTunableNotEqualTo(String value) {
			addCriterion("tunable <>", value, "tunable");
			return (Criteria) this;
		}

		public Criteria andTunableGreaterThan(String value) {
			addCriterion("tunable >", value, "tunable");
			return (Criteria) this;
		}

		public Criteria andTunableGreaterThanOrEqualTo(String value) {
			addCriterion("tunable >=", value, "tunable");
			return (Criteria) this;
		}

		public Criteria andTunableLessThan(String value) {
			addCriterion("tunable <", value, "tunable");
			return (Criteria) this;
		}

		public Criteria andTunableLessThanOrEqualTo(String value) {
			addCriterion("tunable <=", value, "tunable");
			return (Criteria) this;
		}

		public Criteria andTunableLike(String value) {
			addCriterion("tunable like", value, "tunable");
			return (Criteria) this;
		}

		public Criteria andTunableNotLike(String value) {
			addCriterion("tunable not like", value, "tunable");
			return (Criteria) this;
		}

		public Criteria andTunableIn(List<String> values) {
			addCriterion("tunable in", values, "tunable");
			return (Criteria) this;
		}

		public Criteria andTunableNotIn(List<String> values) {
			addCriterion("tunable not in", values, "tunable");
			return (Criteria) this;
		}

		public Criteria andTunableBetween(String value1, String value2) {
			addCriterion("tunable between", value1, value2, "tunable");
			return (Criteria) this;
		}

		public Criteria andTunableNotBetween(String value1, String value2) {
			addCriterion("tunable not between", value1, value2, "tunable");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table kaligia.devicespec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kaligia.devicespec
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 23 09:56:32 EST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}