package com.betterit.kaligia.dao.model.kaligia;

import java.io.Serializable;
import java.util.Date;

public class DeviceInst implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.deviceinst.device_inst_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private Integer deviceInstId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.deviceinst.device_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private Integer deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.deviceinst.serial_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private String serialId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.deviceinst.part_no
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private String partNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.deviceinst.status
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.deviceinst.created_by
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private Integer createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.deviceinst.creation_date
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private Date creationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table kaligia.deviceinst
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.deviceinst.device_inst_id
	 * @return  the value of kaligia.deviceinst.device_inst_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public Integer getDeviceInstId() {
		return deviceInstId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.deviceinst.device_inst_id
	 * @param deviceInstId  the value for kaligia.deviceinst.device_inst_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setDeviceInstId(Integer deviceInstId) {
		this.deviceInstId = deviceInstId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.deviceinst.device_id
	 * @return  the value of kaligia.deviceinst.device_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public Integer getDeviceId() {
		return deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.deviceinst.device_id
	 * @param deviceId  the value for kaligia.deviceinst.device_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setDeviceId(Integer deviceId) {
		this.deviceId = deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.deviceinst.serial_id
	 * @return  the value of kaligia.deviceinst.serial_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public String getSerialId() {
		return serialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.deviceinst.serial_id
	 * @param serialId  the value for kaligia.deviceinst.serial_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setSerialId(String serialId) {
		this.serialId = serialId == null ? null : serialId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.deviceinst.part_no
	 * @return  the value of kaligia.deviceinst.part_no
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public String getPartNo() {
		return partNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.deviceinst.part_no
	 * @param partNo  the value for kaligia.deviceinst.part_no
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setPartNo(String partNo) {
		this.partNo = partNo == null ? null : partNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.deviceinst.status
	 * @return  the value of kaligia.deviceinst.status
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.deviceinst.status
	 * @param status  the value for kaligia.deviceinst.status
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.deviceinst.created_by
	 * @return  the value of kaligia.deviceinst.created_by
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public Integer getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.deviceinst.created_by
	 * @param createdBy  the value for kaligia.deviceinst.created_by
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.deviceinst.creation_date
	 * @return  the value of kaligia.deviceinst.creation_date
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public Date getCreationDate() {
		return creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.deviceinst.creation_date
	 * @param creationDate  the value for kaligia.deviceinst.creation_date
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.deviceinst
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", deviceInstId=").append(deviceInstId);
		sb.append(", deviceId=").append(deviceId);
		sb.append(", serialId=").append(serialId);
		sb.append(", partNo=").append(partNo);
		sb.append(", status=").append(status);
		sb.append(", createdBy=").append(createdBy);
		sb.append(", creationDate=").append(creationDate);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}