package com.betterit.kaligia.dao.model.kaligia;

import java.io.Serializable;
import java.util.Date;

public class EndPointDevices implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.endpointdevices.end_point_id
	 * @mbggenerated  Mon Mar 07 21:27:55 EST 2016
	 */
	private Integer endPointId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.endpointdevices.device_inst_id
	 * @mbggenerated  Mon Mar 07 21:27:55 EST 2016
	 */
	private Integer deviceInstId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.endpointdevices.created_by
	 * @mbggenerated  Mon Mar 07 21:27:55 EST 2016
	 */
	private Integer createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.endpointdevices.creation_date
	 * @mbggenerated  Mon Mar 07 21:27:55 EST 2016
	 */
	private Date creationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.endpointdevices.used_for
	 * @mbggenerated  Mon Mar 07 21:27:55 EST 2016
	 */
	private String usedFor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table kaligia.endpointdevices
	 * @mbggenerated  Mon Mar 07 21:27:55 EST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.endpointdevices.end_point_id
	 * @return  the value of kaligia.endpointdevices.end_point_id
	 * @mbggenerated  Mon Mar 07 21:27:55 EST 2016
	 */
	public Integer getEndPointId() {
		return endPointId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.endpointdevices.end_point_id
	 * @param endPointId  the value for kaligia.endpointdevices.end_point_id
	 * @mbggenerated  Mon Mar 07 21:27:55 EST 2016
	 */
	public void setEndPointId(Integer endPointId) {
		this.endPointId = endPointId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.endpointdevices.device_inst_id
	 * @return  the value of kaligia.endpointdevices.device_inst_id
	 * @mbggenerated  Mon Mar 07 21:27:55 EST 2016
	 */
	public Integer getDeviceInstId() {
		return deviceInstId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.endpointdevices.device_inst_id
	 * @param deviceInstId  the value for kaligia.endpointdevices.device_inst_id
	 * @mbggenerated  Mon Mar 07 21:27:55 EST 2016
	 */
	public void setDeviceInstId(Integer deviceInstId) {
		this.deviceInstId = deviceInstId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.endpointdevices.created_by
	 * @return  the value of kaligia.endpointdevices.created_by
	 * @mbggenerated  Mon Mar 07 21:27:55 EST 2016
	 */
	public Integer getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.endpointdevices.created_by
	 * @param createdBy  the value for kaligia.endpointdevices.created_by
	 * @mbggenerated  Mon Mar 07 21:27:55 EST 2016
	 */
	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.endpointdevices.creation_date
	 * @return  the value of kaligia.endpointdevices.creation_date
	 * @mbggenerated  Mon Mar 07 21:27:55 EST 2016
	 */
	public Date getCreationDate() {
		return creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.endpointdevices.creation_date
	 * @param creationDate  the value for kaligia.endpointdevices.creation_date
	 * @mbggenerated  Mon Mar 07 21:27:55 EST 2016
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.endpointdevices.used_for
	 * @return  the value of kaligia.endpointdevices.used_for
	 * @mbggenerated  Mon Mar 07 21:27:55 EST 2016
	 */
	public String getUsedFor() {
		return usedFor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.endpointdevices.used_for
	 * @param usedFor  the value for kaligia.endpointdevices.used_for
	 * @mbggenerated  Mon Mar 07 21:27:55 EST 2016
	 */
	public void setUsedFor(String usedFor) {
		this.usedFor = usedFor == null ? null : usedFor.trim();
	}
}