package com.betterit.kaligia.dao.model.kaligia;

import java.io.Serializable;
import java.util.Date;

public class EndPoint implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.endpoint.end_point_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private Integer endPointId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.endpoint.name
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.endpoint.description
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.endpoint.type
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.endpoint.status
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.endpoint.site_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private Integer siteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.endpoint.created_by
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private Integer createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.endpoint.creation_date
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private Date creationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table kaligia.endpoint
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.endpoint.end_point_id
	 * @return  the value of kaligia.endpoint.end_point_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public Integer getEndPointId() {
		return endPointId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.endpoint.end_point_id
	 * @param endPointId  the value for kaligia.endpoint.end_point_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setEndPointId(Integer endPointId) {
		this.endPointId = endPointId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.endpoint.name
	 * @return  the value of kaligia.endpoint.name
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.endpoint.name
	 * @param name  the value for kaligia.endpoint.name
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.endpoint.description
	 * @return  the value of kaligia.endpoint.description
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.endpoint.description
	 * @param description  the value for kaligia.endpoint.description
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.endpoint.type
	 * @return  the value of kaligia.endpoint.type
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.endpoint.type
	 * @param type  the value for kaligia.endpoint.type
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.endpoint.status
	 * @return  the value of kaligia.endpoint.status
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.endpoint.status
	 * @param status  the value for kaligia.endpoint.status
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.endpoint.site_id
	 * @return  the value of kaligia.endpoint.site_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public Integer getSiteId() {
		return siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.endpoint.site_id
	 * @param siteId  the value for kaligia.endpoint.site_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.endpoint.created_by
	 * @return  the value of kaligia.endpoint.created_by
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public Integer getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.endpoint.created_by
	 * @param createdBy  the value for kaligia.endpoint.created_by
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.endpoint.creation_date
	 * @return  the value of kaligia.endpoint.creation_date
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public Date getCreationDate() {
		return creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.endpoint.creation_date
	 * @param creationDate  the value for kaligia.endpoint.creation_date
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.endpoint
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", endPointId=").append(endPointId);
		sb.append(", name=").append(name);
		sb.append(", description=").append(description);
		sb.append(", type=").append(type);
		sb.append(", status=").append(status);
		sb.append(", siteId=").append(siteId);
		sb.append(", createdBy=").append(createdBy);
		sb.append(", creationDate=").append(creationDate);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}