package com.betterit.kaligia.dao.model.kaligia;

import java.io.Serializable;

public class LabLog implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.lablog.run_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private Integer runId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.lablog.name
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.lablog.value
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.lablog.unit
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private String unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table kaligia.lablog
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.lablog.run_id
	 * @return  the value of kaligia.lablog.run_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public Integer getRunId() {
		return runId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.lablog.run_id
	 * @param runId  the value for kaligia.lablog.run_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setRunId(Integer runId) {
		this.runId = runId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.lablog.name
	 * @return  the value of kaligia.lablog.name
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.lablog.name
	 * @param name  the value for kaligia.lablog.name
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.lablog.value
	 * @return  the value of kaligia.lablog.value
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.lablog.value
	 * @param value  the value for kaligia.lablog.value
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setValue(String value) {
		this.value = value == null ? null : value.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.lablog.unit
	 * @return  the value of kaligia.lablog.unit
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.lablog.unit
	 * @param unit  the value for kaligia.lablog.unit
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setUnit(String unit) {
		this.unit = unit == null ? null : unit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.lablog
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", runId=").append(runId);
		sb.append(", name=").append(name);
		sb.append(", value=").append(value);
		sb.append(", unit=").append(unit);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}