package com.betterit.kaligia.dao.model.kaligia;

import java.io.Serializable;

public class Privileges implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.privileges.priv_id
	 * @mbggenerated  Fri Mar 11 11:31:47 EST 2016
	 */
	private Integer privId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.privileges.name
	 * @mbggenerated  Fri Mar 11 11:31:47 EST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.privileges.description
	 * @mbggenerated  Fri Mar 11 11:31:47 EST 2016
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table kaligia.privileges
	 * @mbggenerated  Fri Mar 11 11:31:47 EST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.privileges.priv_id
	 * @return  the value of kaligia.privileges.priv_id
	 * @mbggenerated  Fri Mar 11 11:31:47 EST 2016
	 */
	public Integer getPrivId() {
		return privId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.privileges.priv_id
	 * @param privId  the value for kaligia.privileges.priv_id
	 * @mbggenerated  Fri Mar 11 11:31:47 EST 2016
	 */
	public void setPrivId(Integer privId) {
		this.privId = privId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.privileges.name
	 * @return  the value of kaligia.privileges.name
	 * @mbggenerated  Fri Mar 11 11:31:47 EST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.privileges.name
	 * @param name  the value for kaligia.privileges.name
	 * @mbggenerated  Fri Mar 11 11:31:47 EST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.privileges.description
	 * @return  the value of kaligia.privileges.description
	 * @mbggenerated  Fri Mar 11 11:31:47 EST 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.privileges.description
	 * @param description  the value for kaligia.privileges.description
	 * @mbggenerated  Fri Mar 11 11:31:47 EST 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}