package com.betterit.kaligia.dao.model.kaligia;

import java.io.Serializable;
import java.util.Date;

public class RunSegment implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.runsegment.run_segment_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private Integer runSegmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.runsegment.segment_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private Integer segmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.runsegment.run_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private Integer runId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.runsegment.run_no
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private Integer runNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.runsegment.status
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.runsegment.start_time
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.runsegment.end_time
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table kaligia.runsegment
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.runsegment.run_segment_id
	 * @return  the value of kaligia.runsegment.run_segment_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public Integer getRunSegmentId() {
		return runSegmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.runsegment.run_segment_id
	 * @param runSegmentId  the value for kaligia.runsegment.run_segment_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setRunSegmentId(Integer runSegmentId) {
		this.runSegmentId = runSegmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.runsegment.segment_id
	 * @return  the value of kaligia.runsegment.segment_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public Integer getSegmentId() {
		return segmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.runsegment.segment_id
	 * @param segmentId  the value for kaligia.runsegment.segment_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setSegmentId(Integer segmentId) {
		this.segmentId = segmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.runsegment.run_id
	 * @return  the value of kaligia.runsegment.run_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public Integer getRunId() {
		return runId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.runsegment.run_id
	 * @param runId  the value for kaligia.runsegment.run_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setRunId(Integer runId) {
		this.runId = runId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.runsegment.run_no
	 * @return  the value of kaligia.runsegment.run_no
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public Integer getRunNo() {
		return runNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.runsegment.run_no
	 * @param runNo  the value for kaligia.runsegment.run_no
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setRunNo(Integer runNo) {
		this.runNo = runNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.runsegment.status
	 * @return  the value of kaligia.runsegment.status
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.runsegment.status
	 * @param status  the value for kaligia.runsegment.status
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.runsegment.start_time
	 * @return  the value of kaligia.runsegment.start_time
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.runsegment.start_time
	 * @param startTime  the value for kaligia.runsegment.start_time
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.runsegment.end_time
	 * @return  the value of kaligia.runsegment.end_time
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.runsegment.end_time
	 * @param endTime  the value for kaligia.runsegment.end_time
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.runsegment
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", runSegmentId=").append(runSegmentId);
		sb.append(", segmentId=").append(segmentId);
		sb.append(", runId=").append(runId);
		sb.append(", runNo=").append(runNo);
		sb.append(", status=").append(status);
		sb.append(", startTime=").append(startTime);
		sb.append(", endTime=").append(endTime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}