package com.betterit.kaligia.dao.model.kaligia;

import java.io.Serializable;
import java.util.Date;

public class SubjectLog implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.subjectlog.subject_id
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	private Integer subjectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.subjectlog.order_id
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.subjectlog.name
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.subjectlog.value
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.subjectlog.unit
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	private String unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.subjectlog.creation_date
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	private Date creationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.subjectlog.created_by
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	private Integer createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table kaligia.subjectlog
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.subjectlog.subject_id
	 * @return  the value of kaligia.subjectlog.subject_id
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public Integer getSubjectId() {
		return subjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.subjectlog.subject_id
	 * @param subjectId  the value for kaligia.subjectlog.subject_id
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.subjectlog.order_id
	 * @return  the value of kaligia.subjectlog.order_id
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.subjectlog.order_id
	 * @param orderId  the value for kaligia.subjectlog.order_id
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.subjectlog.name
	 * @return  the value of kaligia.subjectlog.name
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.subjectlog.name
	 * @param name  the value for kaligia.subjectlog.name
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.subjectlog.value
	 * @return  the value of kaligia.subjectlog.value
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.subjectlog.value
	 * @param value  the value for kaligia.subjectlog.value
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public void setValue(String value) {
		this.value = value == null ? null : value.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.subjectlog.unit
	 * @return  the value of kaligia.subjectlog.unit
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.subjectlog.unit
	 * @param unit  the value for kaligia.subjectlog.unit
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public void setUnit(String unit) {
		this.unit = unit == null ? null : unit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.subjectlog.creation_date
	 * @return  the value of kaligia.subjectlog.creation_date
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public Date getCreationDate() {
		return creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.subjectlog.creation_date
	 * @param creationDate  the value for kaligia.subjectlog.creation_date
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.subjectlog.created_by
	 * @return  the value of kaligia.subjectlog.created_by
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public Integer getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.subjectlog.created_by
	 * @param createdBy  the value for kaligia.subjectlog.created_by
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}
}