package com.betterit.kaligia.dao.model.kaligia;

import java.io.Serializable;
import java.util.Date;

public class Subject implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.subject.subject_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private Integer subjectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.subject.name
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.subject.dob
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private Date dob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.subject.gender
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.subject.ethnicity
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private String ethnicity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.subject.creation_date
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private Date creationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.subject.created_by
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private Integer createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table kaligia.subject
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.subject.subject_id
	 * @return  the value of kaligia.subject.subject_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public Integer getSubjectId() {
		return subjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.subject.subject_id
	 * @param subjectId  the value for kaligia.subject.subject_id
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.subject.name
	 * @return  the value of kaligia.subject.name
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.subject.name
	 * @param name  the value for kaligia.subject.name
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.subject.dob
	 * @return  the value of kaligia.subject.dob
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public Date getDob() {
		return dob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.subject.dob
	 * @param dob  the value for kaligia.subject.dob
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setDob(Date dob) {
		this.dob = dob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.subject.gender
	 * @return  the value of kaligia.subject.gender
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.subject.gender
	 * @param gender  the value for kaligia.subject.gender
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setGender(String gender) {
		this.gender = gender == null ? null : gender.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.subject.ethnicity
	 * @return  the value of kaligia.subject.ethnicity
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public String getEthnicity() {
		return ethnicity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.subject.ethnicity
	 * @param ethnicity  the value for kaligia.subject.ethnicity
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setEthnicity(String ethnicity) {
		this.ethnicity = ethnicity == null ? null : ethnicity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.subject.creation_date
	 * @return  the value of kaligia.subject.creation_date
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public Date getCreationDate() {
		return creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.subject.creation_date
	 * @param creationDate  the value for kaligia.subject.creation_date
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.subject.created_by
	 * @return  the value of kaligia.subject.created_by
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public Integer getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.subject.created_by
	 * @param createdBy  the value for kaligia.subject.created_by
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.subject
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", subjectId=").append(subjectId);
		sb.append(", name=").append(name);
		sb.append(", dob=").append(dob);
		sb.append(", gender=").append(gender);
		sb.append(", ethnicity=").append(ethnicity);
		sb.append(", creationDate=").append(creationDate);
		sb.append(", createdBy=").append(createdBy);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}