package com.betterit.kaligia.dao.model.kaligia;

import java.io.Serializable;

public class TestDevices implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.testdevices.device_id
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	private Integer deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.testdevices.procedure_id
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	private Integer procedureId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table kaligia.testdevices
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.testdevices.device_id
	 * @return  the value of kaligia.testdevices.device_id
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public Integer getDeviceId() {
		return deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.testdevices.device_id
	 * @param deviceId  the value for kaligia.testdevices.device_id
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public void setDeviceId(Integer deviceId) {
		this.deviceId = deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.testdevices.procedure_id
	 * @return  the value of kaligia.testdevices.procedure_id
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public Integer getProcedureId() {
		return procedureId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.testdevices.procedure_id
	 * @param procedureId  the value for kaligia.testdevices.procedure_id
	 * @mbggenerated  Wed Feb 24 18:50:34 EST 2016
	 */
	public void setProcedureId(Integer procedureId) {
		this.procedureId = procedureId;
	}
}