package com.betterit.kaligia.dao.model.kaligia;

import java.io.Serializable;
import java.util.Date;

public class TestSegment implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.testsegment.segment_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private Integer segmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.testsegment.name
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.testsegment.description
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.testsegment.created_by
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private Integer createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.testsegment.creation_date
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private Date creationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table kaligia.testsegment
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.testsegment.segment_id
	 * @return  the value of kaligia.testsegment.segment_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public Integer getSegmentId() {
		return segmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.testsegment.segment_id
	 * @param segmentId  the value for kaligia.testsegment.segment_id
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setSegmentId(Integer segmentId) {
		this.segmentId = segmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.testsegment.name
	 * @return  the value of kaligia.testsegment.name
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.testsegment.name
	 * @param name  the value for kaligia.testsegment.name
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.testsegment.description
	 * @return  the value of kaligia.testsegment.description
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.testsegment.description
	 * @param description  the value for kaligia.testsegment.description
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.testsegment.created_by
	 * @return  the value of kaligia.testsegment.created_by
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public Integer getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.testsegment.created_by
	 * @param createdBy  the value for kaligia.testsegment.created_by
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.testsegment.creation_date
	 * @return  the value of kaligia.testsegment.creation_date
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public Date getCreationDate() {
		return creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.testsegment.creation_date
	 * @param creationDate  the value for kaligia.testsegment.creation_date
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.testsegment
	 * @mbggenerated  Mon Mar 28 12:28:14 EDT 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", segmentId=").append(segmentId);
		sb.append(", name=").append(name);
		sb.append(", description=").append(description);
		sb.append(", createdBy=").append(createdBy);
		sb.append(", creationDate=").append(creationDate);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}