package com.betterit.kaligia.dao.model.kaligia;

import java.io.Serializable;

public class Users implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.users.user_id
	 * @mbggenerated  Thu Feb 25 22:09:43 EST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.users.name
	 * @mbggenerated  Thu Feb 25 22:09:43 EST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaligia.users.role
	 * @mbggenerated  Thu Feb 25 22:09:43 EST 2016
	 */
	private String role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table kaligia.users
	 * @mbggenerated  Thu Feb 25 22:09:43 EST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.users.user_id
	 * @return  the value of kaligia.users.user_id
	 * @mbggenerated  Thu Feb 25 22:09:43 EST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.users.user_id
	 * @param userId  the value for kaligia.users.user_id
	 * @mbggenerated  Thu Feb 25 22:09:43 EST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.users.name
	 * @return  the value of kaligia.users.name
	 * @mbggenerated  Thu Feb 25 22:09:43 EST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.users.name
	 * @param name  the value for kaligia.users.name
	 * @mbggenerated  Thu Feb 25 22:09:43 EST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaligia.users.role
	 * @return  the value of kaligia.users.role
	 * @mbggenerated  Thu Feb 25 22:09:43 EST 2016
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaligia.users.role
	 * @param role  the value for kaligia.users.role
	 * @mbggenerated  Thu Feb 25 22:09:43 EST 2016
	 */
	public void setRole(String role) {
		this.role = role == null ? null : role.trim();
	}
}