package com.betterit.kaligia.dao.repository.kaligia;

import com.betterit.kaligia.dao.model.kaligia.AppConfig;
import com.betterit.kaligia.dao.model.kaligia.AppConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaligia.appconfig
     *
     * @mbggenerated Mon Mar 28 12:28:14 EDT 2016
     */
    int deleteByExample(AppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaligia.appconfig
     *
     * @mbggenerated Mon Mar 28 12:28:14 EDT 2016
     */
    int deleteByPrimaryKey(Integer configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaligia.appconfig
     *
     * @mbggenerated Mon Mar 28 12:28:14 EDT 2016
     */
    int insert(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaligia.appconfig
     *
     * @mbggenerated Mon Mar 28 12:28:14 EDT 2016
     */
    int insertSelective(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaligia.appconfig
     *
     * @mbggenerated Mon Mar 28 12:28:14 EDT 2016
     */
    List<AppConfig> selectByExample(AppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaligia.appconfig
     *
     * @mbggenerated Mon Mar 28 12:28:14 EDT 2016
     */
    AppConfig selectByPrimaryKey(Integer configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaligia.appconfig
     *
     * @mbggenerated Mon Mar 28 12:28:14 EDT 2016
     */
    int updateByExampleSelective(@Param("record") AppConfig record, @Param("example") AppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaligia.appconfig
     *
     * @mbggenerated Mon Mar 28 12:28:14 EDT 2016
     */
    int updateByExample(@Param("record") AppConfig record, @Param("example") AppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaligia.appconfig
     *
     * @mbggenerated Mon Mar 28 12:28:14 EDT 2016
     */
    int updateByPrimaryKeySelective(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaligia.appconfig
     *
     * @mbggenerated Mon Mar 28 12:28:14 EDT 2016
     */
    int updateByPrimaryKey(AppConfig record);
}