package com.betterit.kaligia.dao.repository.kaligia;

import com.betterit.kaligia.dao.model.kaligia.Device;
import com.betterit.kaligia.dao.model.kaligia.DeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.device
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int deleteByExample(DeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.device
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int deleteByPrimaryKey(Integer deviceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.device
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int insert(Device record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.device
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int insertSelective(Device record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.device
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	List<Device> selectByExample(DeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.device
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	Device selectByPrimaryKey(Integer deviceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.device
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int updateByExampleSelective(@Param("record") Device record, @Param("example") DeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.device
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int updateByExample(@Param("record") Device record, @Param("example") DeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.device
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int updateByPrimaryKeySelective(Device record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.device
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int updateByPrimaryKey(Device record);
}