package com.betterit.kaligia.dao.repository.kaligia;

import com.betterit.kaligia.dao.model.kaligia.EndPointDevices;
import com.betterit.kaligia.dao.model.kaligia.EndPointDevicesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EndPointDevicesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.endpointdevices
	 * @mbggenerated  Sun Mar 20 15:53:29 EDT 2016
	 */
	int deleteByExample(EndPointDevicesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.endpointdevices
	 * @mbggenerated  Sun Mar 20 15:53:29 EDT 2016
	 */
	int insert(EndPointDevices record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.endpointdevices
	 * @mbggenerated  Sun Mar 20 15:53:29 EDT 2016
	 */
	int insertSelective(EndPointDevices record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.endpointdevices
	 * @mbggenerated  Sun Mar 20 15:53:29 EDT 2016
	 */
	List<EndPointDevices> selectByExample(EndPointDevicesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.endpointdevices
	 * @mbggenerated  Sun Mar 20 15:53:29 EDT 2016
	 */
	int updateByExampleSelective(@Param("record") EndPointDevices record,
			@Param("example") EndPointDevicesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.endpointdevices
	 * @mbggenerated  Sun Mar 20 15:53:29 EDT 2016
	 */
	int updateByExample(@Param("record") EndPointDevices record, @Param("example") EndPointDevicesExample example);
}