package com.betterit.kaligia.dao.repository.kaligia;

import com.betterit.kaligia.dao.model.kaligia.SpecimenSpec;
import com.betterit.kaligia.dao.model.kaligia.SpecimenSpecExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpecimenSpecMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.specimenspec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int deleteByExample(SpecimenSpecExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.specimenspec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int insert(SpecimenSpec record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.specimenspec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int insertSelective(SpecimenSpec record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.specimenspec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	List<SpecimenSpec> selectByExample(SpecimenSpecExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.specimenspec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int updateByExampleSelective(@Param("record") SpecimenSpec record, @Param("example") SpecimenSpecExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.specimenspec
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int updateByExample(@Param("record") SpecimenSpec record, @Param("example") SpecimenSpecExample example);
}