package com.betterit.kaligia.dao.repository.kaligia;

import com.betterit.kaligia.dao.model.kaligia.Specimen;
import com.betterit.kaligia.dao.model.kaligia.SpecimenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpecimenMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.specimen
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int deleteByExample(SpecimenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.specimen
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int deleteByPrimaryKey(Integer specimenId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.specimen
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int insert(Specimen record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.specimen
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int insertSelective(Specimen record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.specimen
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	List<Specimen> selectByExample(SpecimenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.specimen
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	Specimen selectByPrimaryKey(Integer specimenId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.specimen
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int updateByExampleSelective(@Param("record") Specimen record, @Param("example") SpecimenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.specimen
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int updateByExample(@Param("record") Specimen record, @Param("example") SpecimenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.specimen
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int updateByPrimaryKeySelective(Specimen record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.specimen
	 * @mbggenerated  Mon Mar 28 12:28:13 EDT 2016
	 */
	int updateByPrimaryKey(Specimen record);
}