package com.betterit.kaligia.dao.repository.kaligia;

import com.betterit.kaligia.dao.model.kaligia.TmpTestResult;
import com.betterit.kaligia.dao.model.kaligia.TmpTestResultExample;
import java.util.List;

public interface TmpTestResultMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kaligia.tmp_testresult
	 * @mbggenerated  Mon Mar 07 21:27:55 EST 2016
	 */
	List<TmpTestResult> selectByExample(TmpTestResultExample example);
}